//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", ConfigurationName="ServiceReference.TestNavWs_Port")]
    public interface TestNavWs_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TestNavWs:HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.HelloWorld_Result> HelloWorldAsync(ServiceReference.HelloWorld request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TestNavWs:StartJob", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.StartJob_Result> StartJobAsync(ServiceReference.StartJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TestNavWs:CheckJob", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CheckJob_Result> CheckJobAsync(ServiceReference.CheckJob request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class HelloWorld
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string inputText;
        
        public HelloWorld()
        {
        }
        
        public HelloWorld(string inputText)
        {
            this.inputText = inputText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class HelloWorld_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string return_value;
        
        public HelloWorld_Result()
        {
        }
        
        public HelloWorld_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartJob", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class StartJob
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string jobId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=1)]
        public string inputJson;
        
        public StartJob()
        {
        }
        
        public StartJob(string jobId, string inputJson)
        {
            this.jobId = jobId;
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartJob_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class StartJob_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string return_value;
        
        public StartJob_Result()
        {
        }
        
        public StartJob_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckJob", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class CheckJob
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string jobId;
        
        public CheckJob()
        {
        }
        
        public CheckJob(string jobId)
        {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckJob_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", IsWrapped=true)]
    public partial class CheckJob_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TestNavWs", Order=0)]
        public string return_value;
        
        public CheckJob_Result()
        {
        }
        
        public CheckJob_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TestNavWs_PortChannel : ServiceReference.TestNavWs_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TestNavWs_PortClient : System.ServiceModel.ClientBase<ServiceReference.TestNavWs_Port>, ServiceReference.TestNavWs_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TestNavWs_PortClient() : 
                base(TestNavWs_PortClient.GetDefaultBinding(), TestNavWs_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TestNavWs_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestNavWs_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(TestNavWs_PortClient.GetBindingForEndpoint(endpointConfiguration), TestNavWs_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestNavWs_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TestNavWs_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestNavWs_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TestNavWs_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestNavWs_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.HelloWorld_Result> ServiceReference.TestNavWs_Port.HelloWorldAsync(ServiceReference.HelloWorld request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.HelloWorld_Result> HelloWorldAsync(string inputText)
        {
            ServiceReference.HelloWorld inValue = new ServiceReference.HelloWorld();
            inValue.inputText = inputText;
            return ((ServiceReference.TestNavWs_Port)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.StartJob_Result> ServiceReference.TestNavWs_Port.StartJobAsync(ServiceReference.StartJob request)
        {
            return base.Channel.StartJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.StartJob_Result> StartJobAsync(string jobId, string inputJson)
        {
            ServiceReference.StartJob inValue = new ServiceReference.StartJob();
            inValue.jobId = jobId;
            inValue.inputJson = inputJson;
            return ((ServiceReference.TestNavWs_Port)(this)).StartJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CheckJob_Result> ServiceReference.TestNavWs_Port.CheckJobAsync(ServiceReference.CheckJob request)
        {
            return base.Channel.CheckJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CheckJob_Result> CheckJobAsync(string jobId)
        {
            ServiceReference.CheckJob inValue = new ServiceReference.CheckJob();
            inValue.jobId = jobId;
            return ((ServiceReference.TestNavWs_Port)(this)).CheckJobAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestNavWs_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestNavWs_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7649/DynamicsNAVCarloTEST/WS/MOTORFORUM DRAMMEN/Codeunit/TestNav" +
                        "Ws?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TestNavWs_PortClient.GetBindingForEndpoint(EndpointConfiguration.TestNavWs_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TestNavWs_PortClient.GetEndpointAddress(EndpointConfiguration.TestNavWs_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            TestNavWs_Port,
        }
    }
}
